version: '3.5'

services:
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - ./out/cassandra_data:/var/lib/cassandra

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:latest
      depends_on:
        - cassandra
      restart: on-failure
      volumes:
        - ./server/cassandra_schema.cql:/schema.cql
      command: /bin/bash -c "sleep 30 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  server:
    container_name: image_server
    build: .
    depends_on:
      - cassandra
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - ./serv_vol:/serv_vol
    environment:
      CASSANDRA_HOST: "cassandra"